package com.mawen.search.core.mapping;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import com.mawen.search.core.document.Document;

import org.springframework.data.mapping.model.SimpleTypeHolder;

/**
 * @author <a href="1181963012mw@gmail.com">mawen12</a>
 * @since 0.0.1
 */
public class ElasticsearchSimpleTypes {

	static final Set<Class<?>> AUTOGENERATED_ID_TYPES;
	private static final Set<Class<?>> ELASTICSEARCH_SIMPLE_TYPES;

	static {
		AUTOGENERATED_ID_TYPES = new HashSet<>(1);
		AUTOGENERATED_ID_TYPES.add(String.class);

		ELASTICSEARCH_SIMPLE_TYPES = new HashSet<>(2);
		ELASTICSEARCH_SIMPLE_TYPES.add(Document.class);
		ELASTICSEARCH_SIMPLE_TYPES.add(Map.class);
	}

	public static final SimpleTypeHolder HOLDER = new SimpleTypeHolder(ELASTICSEARCH_SIMPLE_TYPES, true);

	private ElasticsearchSimpleTypes() {
	}
}
